package com.aicouples.therapy.data.repository

import android.app.Activity
import android.content.Context
import android.content.ContextWrapper
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.aicouples.therapy.BuildConfig
import com.aicouples.therapy.common.Result
import com.aicouples.therapy.common.runCatchingResultSuspend
import com.aicouples.therapy.data.model.ProfileInsert
import com.aicouples.therapy.data.model.UserProfile
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.auth.providers.Google
import io.github.jan.supabase.auth.providers.builtin.IDToken
import io.github.jan.supabase.auth.status.SessionStatus
import io.github.jan.supabase.postgrest.from
import javax.inject.Inject
import javax.inject.Singleton
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.security.MessageDigest
import java.util.UUID

@Singleton
class AuthRepository @Inject constructor(
    private val client: SupabaseClient,
) {
    val sessionStatus: Flow<SessionStatus> = client.auth.sessionStatus

    val isSignedIn: Flow<Boolean> = sessionStatus.map { it is SessionStatus.Authenticated }

    fun currentUserId(): String? = client.auth.currentUserOrNull()?.id

    /**
     * Credential Manager must be launched with an Activity context — Application
     * context cannot show the Google account selector UI.
     */
    suspend fun signInWithGoogle(activityContext: Context): Result<UserProfile> = runCatchingResultSuspend {
        require(BuildConfig.GOOGLE_WEB_CLIENT_ID.isNotBlank()) {
            "GOOGLE_WEB_CLIENT_ID is missing. See user_setup.md."
        }
        val activity = activityContext.findActivity()
            ?: throw IllegalStateException(
                "Google Sign-In requires an Activity context to show the account picker.",
            )

        val nonce = UUID.randomUUID().toString()
        val hashedNonce = sha256(nonce)

        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(BuildConfig.GOOGLE_WEB_CLIENT_ID)
            .setNonce(hashedNonce)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val credentialManager = CredentialManager.create(activity)
        val result = try {
            credentialManager.getCredential(activity, request)
        } catch (e: GetCredentialException) {
            throw IllegalStateException("Google Sign-In failed: ${e.message}", e)
        }

        val credential = result.credential
        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            throw IllegalStateException("Unexpected credential type")
        }

        val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
        client.auth.signInWith(IDToken) {
            idToken = googleIdTokenCredential.idToken
            provider = Google
            this.nonce = nonce
        }

        ensureProfile()
    }

    suspend fun ensureProfile(): UserProfile {
        val user = client.auth.currentUserOrNull()
            ?: throw IllegalStateException("Not authenticated")

        val existing = client.from("profiles")
            .select {
                filter { eq("id", user.id) }
            }
            .decodeSingleOrNull<UserProfile>()

        if (existing != null) return existing

        val metadata = user.userMetadata
        val profile = UserProfile(
            id = user.id,
            email = user.email,
            displayName = metadata?.get("full_name")?.toString()?.trim('"')
                ?: metadata?.get("name")?.toString()?.trim('"')
                ?: user.email?.substringBefore("@"),
            photoUrl = metadata?.get("avatar_url")?.toString()?.trim('"')
                ?: metadata?.get("picture")?.toString()?.trim('"'),
            pairCode = "", // generated by DB default / trigger
            googleId = metadata?.get("sub")?.toString()?.trim('"') ?: metadata?.get("provider_id")?.toString()?.trim('"'),
        )

        // Insert without pair_code — DB default / auth trigger generates it
        client.from("profiles").insert(
            ProfileInsert(
                id = profile.id,
                email = profile.email,
                displayName = profile.displayName,
                photoUrl = profile.photoUrl,
                googleId = profile.googleId,
            ),
        )

        return client.from("profiles")
            .select { filter { eq("id", user.id) } }
            .decodeSingle()
    }

    suspend fun getProfile(): UserProfile? {
        val id = currentUserId() ?: return null
        return client.from("profiles")
            .select { filter { eq("id", id) } }
            .decodeSingleOrNull()
    }

    suspend fun signOut() {
        client.auth.signOut()
    }

    private fun sha256(input: String): String {
        val bytes = MessageDigest.getInstance("SHA-256").digest(input.toByteArray())
        return bytes.joinToString("") { "%02x".format(it) }
    }
}

private fun Context.findActivity(): Activity? {
    var current: Context? = this
    while (current is ContextWrapper) {
        if (current is Activity) return current
        current = current.baseContext
    }
    return current as? Activity
}
